apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    component: web
spec:
  containers:
    - name: client
      image: superknife0512/multi-fe-react
      ports: 
        - containerPort: 3000